---
title: "04 CD subtypes"
author: "Karissa Barthelson"
date: "2026-06-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(magrittr)
library(readxl)
library(qs)

# vis
library(ComplexUpset)
library(ComplexHeatmap)
library(circlize)
library(RColorBrewer)
library(UpSetR)
library(pander)
library(ggeasy)
library(ggfortify)
library(ggpubr)
library(ggrepel)
library(plotly)
library(grid)
library(gridExtra)
library(gridGraphics)
library(viridis)
library(tidytext)
library(pheatmap)
library(patchwork)

# annotations
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(MPO.db)
library(homologene)
library(ndexr)


# enrichemnt
library(clusterProfiler)
library(gprofiler2)
library(ReactomePA)
library(DOSE)


theme_set(theme_light() +
            theme(plot.title = element_text(hjust = 0.5), 
                  strip.text = element_text(face = "bold", colour = "white"),
                  strip.background = element_rect(fill = "grey20")
            )
)

knitr::opts_chunk$set(
  message = F, echo = F, warning = F
)
```

# import & helpers
```{r}

# Define path
base_path <- "data/results/adultchildsubtypes v2"

# Read enrichment files
enrichment_dfs.2 <- 
  list.files(base_path, recursive = TRUE, full.names = TRUE) %>%
  grep(pattern = "network_colocalization_enrichment", 
       value = TRUE) %>% 
  set_names(
    str_replace(., 
                pattern = "/network_colocalization_enrichment.csv",
                replacement = ""
    ) %>% 
      str_remove(
        pattern = paste0(base_path, "/")
      )
  ) %>%   
  map(read.csv) %>%
  imap(~ mutate(.x, comparison = .y)) %>% 
  bind_rows() %>%
  dplyr::filter(z_comb == 3, z_12 == 1.5) %>%
  pivot_longer(
    cols = c(observed_overlap, expected_overlap_mean),
    names_to = "type",
    values_to = "value"
  ) %>%
  mutate(
    type = recode(type,
                  "observed_overlap" = "observed",
                  "expected_overlap_mean" = "expected")
  ) %>% 
  mutate(source = "GWAS only (no parental proxy)")


base_path <- "data/results/adultchildsubtypes v2"

# Read enrichment files
node_metadata <- 
  list.files(base_path, recursive = TRUE, full.names = TRUE) %>%
  grep(pattern = "nodes_meta", 
       value = TRUE) %>% 
  set_names(
    str_replace(., 
                pattern = "/overlapping_nodes_metadata.csv",
                replacement = ""
    ) %>% 
      str_remove(
        pattern = paste0(base_path, "/")
      )
  ) %>%   
  map(read.csv) %>%
  imap(~ mutate(.x, comparison = .y))

genesets_v2 = list.files("data/genesets/v2/adultchildsubtypes", full.names = T) %>% 
  sapply(read.csv, simplify = F) %>% 
  set_names(
    names(.) %>%
      str_remove("data/genesets/v2/adultchildsubtypes/") %>% 
      str_remove(".csv") %>% 
      str_remove("_list.txt") %>% 
      str_remove("_v2")
  )

nodes <- readRDS("data/R_objects/network/nodes.rds")

# run KEGG ORA
runKEGG = function(geneset) {

  uv =   bitr(nodes, 
                fromType = "SYMBOL", toType = "ENTREZID", 
                OrgDb ="org.Hs.eg.db") %>% 
    .$ENTREZID
  
  bitr(geneset, 
       fromType = "SYMBOL", toType = "ENTREZID", 
     OrgDb ="org.Hs.eg.db") %>% 
  .$ENTREZID %>%
  enrichKEGG(
    organism = 'hsa',
    universe = uv,
    pvalueCutoff = 0.05)
}
```

## plot the obs v exp ratio
```{r}
enrichment_dfs.2 %<>% 
  dplyr::filter(
    z_comb == 3, z_12 == 1.5, 
    ) %>% 
  mutate(
    # use the childhood vector to extract the CD seed gene name
    CD = str_remove(comparison, "_(AD|ALS|PD|DLB|FTLD|brain_malform)$"), 
    adult = str_extract(comparison, "(AD|ALS|PD|DLB|FTLD|brain_malform)$"), 
    CD = case_when(
      grepl(CD, pattern = "1A") ~ "Lysosomal disorders", 
      grepl(CD, pattern = "1B") ~ "Other disorders of lipid metabolism & transport", 
      grepl(CD, pattern = "1C") ~ "Disorders of amino acid & other organic acid metabolism", 
      grepl(CD, pattern = "1D") ~ "Vitamin-responsive inborn errors of metabolism", 
      grepl(CD, pattern = "1E") ~ "Disorders of mineral absorption & transport", 
      grepl(CD, pattern = "1F") ~ "Peroxisomal diseases", 
      grepl(CD, pattern = "1G") ~ "Mitochondrial disorders", 
      grepl(CD, pattern = "1H") ~ "Other inborn errors of metabolism", 
      grepl(CD, pattern = "2_") ~ "Leukodystrophies not notherwise categorised", 
      grepl(CD, pattern = "3_") ~ "Neurodegeneration with brain iron accumulation", 
      grepl(CD, pattern = "4_") ~ "Diseases not otherwise categorised",
      TRUE ~ CD) %>% str_wrap(width = 30), 
    
    facet.order = case_when(
      grepl(comparison, pattern = "1A") ~ 1, 
      grepl(comparison, pattern = "1E") ~ 2, 
      TRUE ~ 9
    )
    
    ) %>%  
  dplyr::filter(type == "observed") %>% 
  mutate(FDR = p.adjust(empirical_p, "fdr")) 

enrichment_dfs.2 %>%   
  ggplot(
    aes(x = obs_exp, y = reorder(adult, obs_exp))
  ) +
  geom_col(
    aes(fill = -log10(FDR), alpha = FDR < 0.05), 
    colour = "grey50", position = "dodge", 
    width = 0.75
  ) +
  scale_fill_viridis_c() +
  scale_alpha_manual(values = c(0.1, 1)) +
  labs(
    x = "observed / expected", 
    y = "Disease"
  ) +
  facet_wrap(~reorder(CD, facet.order), ncol = 3) 
```

## ORA KEGG on whole subnets:
```{r}
# define the significant colocs. 
keep.subnets = enrichment_dfs.2 %>% 
  dplyr::filter(
    z_comb == 3, z_12 == 1.5, 
    FDR < 0.05
) %>% 
  .$comparison %>% unique

ORA.results.whole.subnets.kegg <- node_metadata[keep.subnets] %>% 
  sapply(function(x) {
    x$X %>%
      runKEGG
  }, simplify = F)
```


```{r}
keep = ORA.results.whole.subnets.kegg %>% 
  lapply(as_tibble) %>% 
  bind_rows(.id = "subnet") %>% 
  group_by(Description) %>% 
  summarise(n = n()) %>% 
  arrange(-n) %>% 
  dplyr::filter(n >= 5) %>% 
  .$Description

keep

mat <- 
  ORA.results.whole.subnets.kegg %>% 
  lapply(as_tibble) %>% 
  bind_rows(.id = "subnet") %>% 
  dplyr::filter(Description %in% keep) %>%
  mutate(
    score = -log10(p.adjust), 
    # child = str_extract(subnet, pattern = "CD_.{1,2}"),
    # subnet = paste0(adult, "_", child),
    # subnet = str_remove(subnet, pattern = "_DLB$|_AD$|_FTLD$|_PD$|_ALS$"),
    .after = subnet
    ) %>% 
  dplyr::select(subnet, Description, score) %>%
  distinct() %>%
  arrange(subnet) %>% 
  pivot_wider(names_from = subnet, values_from = score) %>% 
  column_to_rownames("Description") %>%
  as.matrix() 

# Parse subnet names into adult and child components
subnet.meta = colnames(mat) %>%
  as_tibble() %>%
  rename(subnet = value) %>%
  mutate(
    adult = str_extract(subnet, "AD|DLB|PD|ALS|FTLD"),
    CD = str_extract(subnet, "CD_[^_]+_[^_]+"),
    CD = case_when(
      grepl("1A", CD) ~ "Lysosomal disorders",
      grepl("1B", CD) ~ "Other disorders of lipid metabolism & transport",
      grepl("1C", CD) ~ "Disorders of amino acid & other organic acid metabolism",
      grepl("1D", CD) ~ "Vitamin-responsive inborn errors of metabolism",
      grepl("1E", CD) ~ "Disorders of mineral absorption & transport",
      grepl("1F", CD) ~ "Peroxisomal diseases",
      grepl("1G", CD) ~ "Mitochondrial disorders",
      grepl("1H", CD) ~ "Other inborn errors of metabolism",
      grepl("2_", CD) ~ "Leukodystrophies not otherwise categorised",
      grepl("3_", CD) ~ "Neurodegeneration with brain iron accumulation",
      grepl("4_", CD) ~ "Diseases not otherwise categorised"
    ) %>% str_wrap(width = 30)
    )

# Colour palettes
adult.cols = setNames(
  viridis_pal(option = "magma", begin = 0.5)(5),
  unique(subnet.meta$adult)
)

cd.cols = setNames(
  colorRampPalette(brewer.pal(8, "Pastel2"))(n_distinct(subnet.meta$CD)),
  unique(subnet.meta$CD)
)

col_ann = HeatmapAnnotation(
 `Childhood disease` = subnet.meta$CD,
  `Adult disease`     = anno_simple(
    subnet.meta$adult,
    col     = adult.cols[subnet.meta$adult],
    pch     = subnet.meta$adult,
    pt_size = unit(4, "mm"),
    gp      = gpar(fontsize = 8, fontface = "bold")
  ),
  col = list(
    `Childhood disease` = cd.cols
  ),
  annotation_name_gp  = gpar(fontsize = 12)
  # annotation_legend_param = list(
  #   `Childhood disease` = list(
  #     labels_gp = gpar(fontsize = 8)
  #   )
  # )
)

# replace NA (not enriched) with 0
mat[is.na(mat)] <- 0

pdf("output/plots4publication/Fig3b.pdf", width = 18, height = 11)
Heatmap(
  mat,
  name = "-log10(FDR)", 
  border = "black",
  rect_gp = gpar(color = "black"),
  col = colorRamp2(
    c(0, 0.0001, seq(0.0001, max(mat), length.out = 7)),
    viridis(9)
  ),
  
  cell_fun = function(j, i, x, y, width, height, fill) {
  if (mat[i, j] == 0) {
    grid.rect(x, y, width, height, gp = gpar(fill = "white", col = "black"))
  }
},
  
  cluster_rows = TRUE,
  cluster_columns = T,
  
  top_annotation  = col_ann,
  column_split = subnet.meta$CD,
  
  show_row_names = TRUE,
  show_column_names = FALSE,
  
  row_names_gp = gpar(fontsize = 16, face = "bold"),
  column_names_gp = gpar(fontsize = 16),
  
  column_title = "Coloc subnetworks",
  row_title = "KEGG pathways"
) %>% 
  draw(
    heatmap_legend_side = "left", annotation_legend_side = "left", 
    padding = unit(c(2, 2, 2, 50), "mm"))
dev.off()
```


# ORA of MPO terms

We can also run mouse MPO enrichment analysis
```{r}
# this was obtained fromhttps://www.informatics.jax.org/downloads/reports/MGI_PhenoGenoMP.rpt

mm_symbol2mp_id = 
  read_delim(
    "data/MPO/HMD_HumanPhenotype.txt", delim = "\t") %>% 
  dplyr::select(1,4) %>% 
  set_colnames(
    c("mm_symbol", "MP_id")
  ) %>% 
  mutate(
    mm_symbol = str_remove(mm_symbol, pattern = "<.+")
  )

# mpid 2 mp name
mpo_mgi <- AnnotationDbi::select(
  MPO.db,
  keys    = keys(MPO.db, keytype = "mpid"),
  columns = c("mpid", "term"),
  keytype = "mpid"
) %>% 
  dplyr::select(
    MP_id = mpid, mp_full_name = term
  ) %>% 
  as_tibble

# mouse name to human name
mm2hs <- homologene(
  genes  = unique(mm_symbol2mp_id$mm_symbol),
  inTax  = 10090,  # mouse
  outTax = 9606    # human
) %>% 
  dplyr::select(
    mm_symbol = `10090`, hs_symbol = `9606`, 
    mm_entrez = `10090_ID`, hs_entrez = `9606_ID`
  ) %>% 
  mutate(across(everything(), as.character)) %>% 
  as_tibble

# join everything
mpo.df <- mm_symbol2mp_id %>% 
   left_join(mpo_mgi) %>% 
  left_join(mm2hs)

mpo.df.hs.entrez = 
  mpo.df %>% 
  dplyr::filter(hs_symbol %in% nodes) %>% 
  dplyr::select(mp_full_name, hs_entrez) %>% 
  arrange(mp_full_name)

```

```{r}
run.ORA.MPO = function(input) {
  enricher(
  gene          = bitr(input, 
                       fromType = "SYMBOL", toType = "ENTREZID", 
                       OrgDb ="org.Hs.eg.db") %>% .$ENTREZID,
  TERM2GENE     = mpo.df.hs.entrez,
  pvalueCutoff  = 0.05,
  minGSSize     = 5,
  maxGSSize     = 500,
  qvalueCutoff  = 0.05
)
}
```
```{r}
fs8a = run.ORA.MPO(node_metadata$CD_1A_lyso_PD$X) %>% 
  as_tibble() %>% 
  mutate(network = "LysoPD") %>% 
  bind_rows(
    run.ORA.MPO(node_metadata$CD_1A_lyso_DLB$X) %>% 
      as_tibble %>% 
      mutate(
        network = "LysoDLB"
      )
  ) %>% 
  mutate(
    source = "MPO"
  ) %>% 
  bind_rows(
    runKEGG(node_metadata$CD_1A_lyso_PD$X) %>% 
      as_tibble() %>% 
      mutate(network = "LysoPD") %>% 
      bind_rows(
        runKEGG(node_metadata$CD_1A_lyso_DLB$X) %>% 
          as_tibble %>% 
          mutate(
            network = "LysoDLB"
          )
      ) %>% 
      mutate(source = "KEGG")
  ) %>% 
  group_by(Description, source) %>% 
  mutate(
    category = case_when(
      n_distinct(network) == 2 ~ 1,
      network == "LysoPD" ~ 2,
      network == "LysoDLB" ~ 3
    ), 
    source = factor(source, levels = c("MPO", "KEGG"))
  ) %>% 
  ungroup() %>% 
  ggplot(
    aes(
      x = network,
      y = reorder(Description, -category)
    )
  ) +
  geom_tile(
    aes(fill = FoldEnrichment)
  ) +
    geom_label(
          aes(
      label = p.adjust %>% signif(2)
      
      )
    ) +
  scale_fill_viridis_c() +
  facet_wrap(~source, 
             nrow = 1, ncol = 2, scales = "free_y") +
  labs(
    x = "Subnetwork",
    y = NULL
  ) +
   theme(
    strip.text = element_text(size = 12),
    text = element_text(size = 14),
    plot.title = element_text(size = 14, face = "bold"),
    legend.position = "bottom",
    #axis.title.x = element_blank(),
    plot.background = element_blank(),
    panel.grid = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_blank(), 
   ) 
```
# ORA KEGG on communities
```{r}
base_path <- "data/results/adultchildsubtypes v2"

# Read enrichment files
communities <- 
  list.files(base_path, recursive = TRUE, full.names = TRUE) %>%
  grep(pattern = "gprofi", 
       value = TRUE) %>% 
  set_names(
    str_replace(., 
                pattern = "/gprofiler_analysis_results.csv",
                replacement = ""
    ) %>% 
      str_remove(
        pattern = paste0(base_path, "/")
      )
  ) %>%   
  map(read.csv) %>%
  imap(~ mutate(.x, comparison = .y))


# communities$CD_1A_lyso_PD %>% 
#   split(f = .$Cluster) %>% 
#   sapply(function(x) {
#     x$genes %>% 
#       str_split(pattern = " ", simplify = F) %>% 
#       unlist 
#       #runKEGG
#   })


ORA.results.genes.in.communities <- 
  list(
    lysoPD = communities$CD_1A_lyso_PD %>% 
      split(f = .$Cluster) %>% 
      sapply(function(x) {
        x$genes %>% 
          str_split(pattern = " ", simplify = F) %>% 
          unlist %>% 
          runKEGG
      }), 
      
      lysoDLB = communities$CD_1A_lyso_DLB %>% 
        split(f = .$Cluster) %>% 
        sapply(function(x) {
          x$genes %>% 
            str_split(pattern = " ", simplify = F) %>% 
            unlist %>% 
            runKEGG
        }) 
      )
```

# LysoPD and LysoDLB
## is there sig overlap
```{r}
# Define your gene sets
lyso_DLB = node_metadata$CD_1A_lyso_DLB$X
lyso_PD  = node_metadata$CD_1A_lyso_PD$X

# Background = all genes in the interactome
background =  nodes

# Overlap
overlap = intersect(lyso_DLB, lyso_PD)

# Contingency table for Fisher's exact test
#               In PD    Not in PD
# In DLB        a        b
# Not in DLB    c        d

a = length(overlap)
b = length(lyso_DLB) - a
c = length(lyso_PD)  - a
d = length(background) - (a + b + c)

mat = matrix(c(a, b, c, d), nrow = 2,
             dimnames = list(
               c("In_DLB", "Not_in_DLB"),
               c("In_PD",  "Not_in_PD")
             ))
mat

fisher.test(mat, alternative = "greater")

phyper(q = 87, m = 289, n = N - 289, k = 436, lower.tail = FALSE)
```


# figs

## Figure S8
```{r}

  
  (run_upset.ORA("Lysosome biogenesis") | 
     run_upset.ORA("Sphingolipid metabolism") | 
     run_upset.ORA("Phagocytosis") |
     run_upset.ORA("Sphingolipid signaling pathway") |
     run_upset.ORA("Other glycan degradation")  
   ) +
  plot_annotation(tag_levels = list(LETTERS[2:6])) +
  plot_layout(axes = "collect") +
  
ggsave("output/plots4publication/supp/S8b.pdf", 
       height = 5, 
       width = 16)
```
